### ISSUE TITLE
Fails to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by mspaulding06** [maitria/avi#20]
I tried running avi on Ubuntu and that failed with the following error.  I think there is supposed to be an `avi_jni.so` file that gets installed but I don't see it.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no avi_jni in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at avi.terminal.Terminal.start(Terminal.java:6)
	at avi.core$_main$reify__2863.setup(core.clj:47)
	at avi.core$run.invokeStatic(core.clj:40)
	at avi.core$run.invoke(core.clj:37)
	at avi.core$_main.invokeStatic(core.clj:65)
	at avi.core$_main.doInvoke(core.clj:45)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at avi.core.main(Unknown Source)
```

I installed avi by running `sudo lein install`.

Lein 2.6.1
Clojure 1.8.0
Java OpenJDK 1.8.0_91
Ubuntu 16.04

**Comment by eraserhd** [comment]
@mspaulding06 Been busy lately, but this is now fixed.

**Comment by mspaulding06** [comment]
Thanks!  It's working for me now.
