### ISSUE TITLE
Compiling avi.brackets fails with "Unable to resolve spec: :avi.color/color"

### ISSUE THREAD

**Issue by wodin** [maitria/avi#32]
```
Compiling avi.brackets
java.lang.Exception: Unable to resolve spec: :avi.color/color, compiling:(layout.clj:11:1)
Exception in thread "main" java.lang.Exception: Unable to resolve spec: :avi.color/color, compiling:(layout.clj:11:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler.compile1(Compiler.java:7493)
	at clojure.lang.Compiler.compile(Compiler.java:7560)
	at clojure.lang.RT.compile(RT.java:408)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7596.invoke(core.clj:6007)
	at clojure.core$load.invokeStatic(core.clj:6006)
	at clojure.core$load.doInvoke(core.clj:5990)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5811)
	at clojure.core$load_one.invoke(core.clj:5806)
	at clojure.core$load_lib$fn__7541.invoke(core.clj:5851)
	at clojure.core$load_lib.invokeStatic(core.clj:5850)
	at clojure.core$load_lib.doInvoke(core.clj:5831)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5888)
	at clojure.core$load_libs.doInvoke(core.clj:5872)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5910)
	at clojure.core$require.doInvoke(core.clj:5910)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at avi.editor$loading__7482__auto____2600.invoke(editor.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	at clojure.lang.Compiler.compile1(Compiler.java:7493)
	at clojure.lang.Compiler.compile1(Compiler.java:7483)
	at clojure.lang.Compiler.compile(Compiler.java:7560)
	at clojure.lang.RT.compile(RT.java:408)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7596.invoke(core.clj:6007)
	at clojure.core$load.invokeStatic(core.clj:6006)
	at clojure.core$load.doInvoke(core.clj:5990)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5811)
	at clojure.core$load_one.invoke(core.clj:5806)
	at clojure.core$load_lib$fn__7541.invoke(core.clj:5851)
	at clojure.core$load_lib.invokeStatic(core.clj:5850)
	at clojure.core$load_lib.doInvoke(core.clj:5831)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5888)
	at clojure.core$load_libs.doInvoke(core.clj:5872)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5910)
	at clojure.core$require.doInvoke(core.clj:5910)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at avi.brackets$loading__7482__auto____1230.invoke(brackets.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	at clojure.lang.Compiler.compile1(Compiler.java:7493)
	at clojure.lang.Compiler.compile1(Compiler.java:7483)
	at clojure.lang.Compiler.compile(Compiler.java:7560)
	at clojure.lang.RT.compile(RT.java:408)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7596.invoke(core.clj:6007)
	at clojure.core$load.invokeStatic(core.clj:6006)
	at clojure.core$load.doInvoke(core.clj:5990)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5811)
	at clojure.core$compile$fn__7601.invoke(core.clj:6017)
	at clojure.core$compile.invokeStatic(core.clj:6017)
	at clojure.core$compile.invoke(core.clj:6009)
	at user$eval30$fn__39.invoke(form-init470742303365994994.clj:1)
	at user$eval30.invokeStatic(form-init470742303365994994.clj:1)
	at user$eval30.invoke(form-init470742303365994994.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6946)
	at clojure.lang.Compiler.eval(Compiler.java:6936)
	at clojure.lang.Compiler.eval(Compiler.java:6936)
	at clojure.lang.Compiler.load(Compiler.java:7398)
	at clojure.lang.Compiler.loadFile(Compiler.java:7336)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Unable to resolve spec: :avi.color/color
	at clojure.spec$the_spec.invokeStatic(spec.clj:107)
	at clojure.spec$spec_impl.invokeStatic(spec.clj:787)
	at clojure.spec$spec_impl.invokeStatic(spec.clj:783)
	at clojure.spec$def_impl.invokeStatic(spec.clj:275)
	at clojure.spec$def_impl.invoke(spec.clj:271)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	... 90 more
Compilation failed: Subprocess failed
$ git grep avi.color/color
src/avi/layout.clj:(s/def ::foreground :avi.color/color)
src/avi/layout.clj:(s/def ::background :avi.color/color)
```

Java HotSpot(TM) 64-Bit Server VM 1.8.0_91-b14

**Comment by eraserhd** [comment]
Thanks for the report!  I have a fix that will be in `master` shortly.
